name: ci

on:
  # Kjør automatisk når gradle-workflowen er ferdig
  workflow_run:
    workflows: ["gradle.yml"]
    types: [completed]
  # Og la oss kunne trigge manuelt
  workflow_dispatch:

jobs:
  docker-build-push:
    # Kjør kun når: (A) trigget manuelt, eller (B) gradle.yml var "success" og branchen er main
    if: ${{ github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'workflow_run' &&
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main') }}

    runs-on: ubuntu-latest

    steps:
      # Sjekk ut riktig commit
      - name: Checkout (from workflow_run)
        if: ${{ github.event_name == 'workflow_run' }}
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.workflow_run.repository.full_name }}
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Checkout (manual)
        if: ${{ github.event_name != 'workflow_run' }}
        uses: actions/checkout@v4

      # Multi-arch bygg
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Logg inn til Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Finn repo-navnet (trengs fordi workflow_run har et annet event-objekt)
      - name: Compute image tag
        id: meta
        run: |
          if [ "${{ github.event_name }}" = "workflow_run" ]; then
            echo "REPO_NAME=${{ github.event.workflow_run.repository.name }}" >> $GITHUB_ENV
          else
            echo "REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV
          fi

      # Bygg & push runtime-image
      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: .
          # behold denne linja hvis Dockerfile har:  FROM ... AS final
          target: final
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
